In [1]:
%matplotlib inline

In [26]:
import cv2

import numpy as np
import numpy.fft as fft
import matplotlib as mpl

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import HTML

mpl.rcParams['image.cmap'] = "gray"  # show images as grayscale by default
image = cv2.imread("sample-02.png")
# cv2.imshow("Image", image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
b, g, r = cv2.split(image)
print(image[0:2,0:2,:])


[[[26 24 24]
  [24 24 24]]

 [[25 25 25]
  [24 24 24]]]


In [34]:
def linearWeight(pixel_value):
    try:
        """ Linear weighting function based on pixel intensity that reduces the
		weight of pixel values that are near saturation.

		The weighting function should be a piecewise linear function:

							   /  z - Zmin,      z <= (Zmin + Zmax)/2
			linearWeight(z) = |
							   \  Zmax - z,      z > (Zmin + Zmax)/2

		Where z is a pixel intensity value, Zmax=255 (largest uint8 intensity),
		and Zmin=0 (smallest uint8 intensity).

		Parameters
		----------
		pixel_value : np.uint8
			A pixel intensity value from 0 to 255

		Returns
		-------
		weight : np.float64
			The weight corresponding to the input pixel intensity

		See Also
		--------
		"Recovering High Dynamic Range Radiance Maps from Photographs",
			Debevec & Malik (available under resources on T-Square)
		"""
        z_min, z_max = 0., 255.
        case_value = (z_min + z_max) / 2
        if type(pixel_value) == np.array or type(pixel_value) == np.ndarray:
            # Added so I can process images much faster by using numpy.along_axis
            case_1 = pixel_value[pixel_value <= case_value]
            case_1 = case_1 - z_min
            case_2 = pixel_value[pixel_value > case_value]
            case_2 = z_max - case_2
            result = np.hstack((case_1,case_2))
            return result
        else:
            if pixel_value <= case_value:
                return pixel_value - z_min
            elif pixel_value > case_value:
                return z_max - pixel_value
    except Exception as LinearWeightException:
        print("Exception occurred while executing function 'LinearWeight'.\n", LinearWeightException)


In [35]:
test = np.asarray([[[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3]]])
print(test)
result = np.apply_along_axis(linearWeight, 2, test)
print(result)


# new_b = np.apply_along_axis(multBy2, 0, b)
# new_g = np.apply_along_axis(multBy2, 0, g)
# new_r = np.apply_along_axis(multBy2, 0, r)
# new_image = cv2.merge((new_b, new_g, new_r))
# cv2.imshow("Image", image)
# cv2.imshow("B Channel", b)
# cv2.imshow("G Channel", g)
# cv2.imshow("R Channel", r)
# cv2.imshow("New Image", new_image)
# cv2.imshow("New B Channel", new_b)
# cv2.imshow("New G Channel", new_g)
# cv2.imshow("New R Channel", new_r)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
pixel type:  <class 'numpy.ndarray'>
HAY

 T: 
 [1 2 3]
Here is p:  [1. 2. 3.]

T after first case:
 [1 2 3]
Here is j:  []

T after second case:
 [1 2 3]
Here is result:  [1. 2. 3.]
pixel type:  <class 'numpy.ndarray'>
HAY

 T: 
 [1 2 3]
Here is p:  [1. 2. 3.]

T after first case:
 [1 2 3]
Here is j:  []

T after second case:
 [1 2 3]
Here is result:  [1. 2. 3.]
pixel type:  <class 'numpy.ndarray'>
HAY

 T: 
 [1 2 3]
Here is p:  [1. 2. 3.]

T after first case:
 [1 2 3]
Here is j:  []

T after second case:
 [1 2 3]
Here is result:  [1. 2. 3.]
pixel type:  <class 'numpy.ndarray'>
HAY

 T: 
 [1 2 3]
Here is p:  [1. 2. 3.]

T after first case:
 [1 2 3]
Here is j:  []

T after second case:
 [1 2 3]
Here is result:  [1. 2. 3.]
pixel type:  <class 'numpy.ndarray'>
HAY

 T: 
 [1 2 3]
Here is p:  [1. 2. 3.]

T after first case:
 [1 2 3]
Here is j:  []

T after second case:
 [1 2 3]
Here is result:  